table 'Manual Targets'
	lineageTag: 151e69d7-ea3b-477c-a1a4-6910dffb3781

	column 'Region Code'
		dataType: string
		lineageTag: 2d28cf76-8e57-4432-9612-0c8904c86888
		summarizeBy: none
		sourceColumn: Region Code

		annotation SummarizationSetBy = Automatic

	column Target
		dataType: int64
		formatString: 0
		lineageTag: 320318fa-63e6-44fb-ac25-a461867c26e3
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

	partition 'Manual Targets' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8vMPCvFQ0lEyNDIwMDBQitWJVgr2DwULWZrCRFwdg0OUdJQszGEC4a5gAUMDQ7BILAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Region Code" = _t, Target = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Region Code", type text}, {"Target", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

